### ISSUE TITLE
"Unable to process Pull Request Link."

### ISSUE THREAD

**Issue by enricobattocchi** [alandtse/pr_custom_component#13]
## Version of the custom_component

0.2.0

## Describe the bug

- Add PR Custom Component via HACS
- restart
- add integration
- look for "PR custom component"
- in the modal, add the URL for any Home Assistant PR, such as:
  - https://github.com/home-assistant/core/pull/46558 (the original Tesla PR mentioned by the author)
  - https://github.com/home-assistant/core/pull/91600 (the one I was trying to use)
  - https://github.com/home-assistant/core/pull/91714 (yet another one)
- see that you get `Unable to process Pull Request Link.`

**Comment by muraj238** [comment]
I have the same problem, maybe something in the github api changed?

**Comment by muraj238** [comment]
Just remove the 'loop' argument of the async_timeout in the api.py and it's working again.

**Comment by alandtse** [comment]
Thanks. If you submit a PR, happy to merge it.
